sms_survey/sms_survey/urls.py
from django.conf.urls import url

from engagement.views import index, send_sms, chikka_proxy, chikka_receiver

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^send_sms/$', send_sms, name='send_sms'),
    url(r'^chikka_receiver/$', chikka_receiver, name='chikka_receiver'),
    

    # This is only need for testing locally
    url(r'^api/send_sms/$', chikka_proxy, name='chikka_proxy')
]

sms_survey/engagement/models.py
from django.db import models

# Create your models here.

class Messages(models.Model):
    mobile_number = models.CharField(max_length=20)
    message = models.TextField()

sms_survey/engagement/views.py
import requests
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from .models import Messages

# Create your views here.
def  index(request):
    return render(request, 'index.html', {"messages": Messages.objects.all()})


def send_sms(request):
    if request.method == "POST":
        data = {
            "contact": request.POST.get('contact'),
            "message": request.POST.get('message'),
        }
        requests.post("http://www.chikka.com:8000/api/send_sms/", data=data)
        return redirect("/")
    return render(request, 'send_sms.html')


@csrf_exempt
def chikka_receiver(request):
    Messages.objects.create(
        mobile_number=request.POST.get('mobile_number'),
        message=request.POST.get('message')
    )
    return HttpResponse({"message": "Success"})


def chikka_proxy(request):
    return HttpResponse({"message": "Success"})

sms_survey/engagement/templates/index.html
<html>
    <title>Surveyor</title>
    <body>
        <header>Surveyor</header>
        <a href="/send_sms/" id="id_send_sms_page">Want to send SMS, click here!</a>

        <table id="id_table_replies">
        <tr></tr>
        {% for message in messages %}
            <tr>
                <td>{{ message.mobile_number }}</td>
                <td>{{ message.message }}</td>
            </tr>
        {% endfor %}
        </table>

    </body>
</html>

sms_survey/engagement/templates/send_sms.html
<!DOCTYPE html>
<html>
<head>
	<title>Send SMS</title>
</head>
<body>
<header>Fill this information to send an SMS</header>

<form method="POST">
	{% csrf_token %}
	<input type="text" id="id_contact" name="contact" placeholder="Enter phone number" />
	<textarea id="id_message" name="message" placeholder="Enter your message"></textarea>
	<button type="submit" id="id_send_sms">Send SMS</button>
</form>
</body>
</html>